### ISSUE TITLE
ESPHOME Config for LilyGo-T-RGB

### ISSUE THREAD

**Issue by moimart** [Xinyuan-LilyGO/LilyGo-T-RGB#85]
Hi,

I'm trying to get the LilyGo-T-RGB configure properly for ESPHOME and I'm following the schematics. So far I got this:

Only showing relevant part I have so far for the display:

```
spi:
  clk_pin: GPIO33
  mosi_pin: GPIO35
  miso_pin: GPIO34

display:
  - platform: st7701s
    dimensions:
      width: 480
      height: 480
    de_pin: GPIO45

    # Control Pins from Schematic
    hsync_pin: GPIO37
    vsync_pin: GPIO47
    pclk_pin: GPIO42

    # Data Pins from Schematic (assuming standard RGB565 mapping)
    data_pins:
      # Blue: DB0-DB4
      blue:
        - GPIO44  # DB0
        - GPIO21  # DB1
        - GPIO18  # DB2
        - GPIO17  # DB3
        - GPIO16  # DB4
      # Green: DB5-DB10
      green:
        - GPIO15  # DB5
        - GPIO14  # DB6
        - GPIO13  # DB7
        - GPIO12  # DB8
        - GPIO11   # DB9
        - GPIO10   # DB10
      # Red: DB11-DB15
      red:
        - GPIO9   # DB11
        - GPIO43   # DB12
        - GPIO7   # DB13
        - GPIO6   # DB14
        - GPIO5   # DB15
```

Anything here that might be wrong? Especially around the SPI?

**Comment by lewisxhe** [comment]
You cannot use ESPHOME because you need the GPIO expansion chip to transmit the display initialization sequence. ESPHOME does not have this method.

**Comment by Bogdanel** [comment]
Hello, have you had any success with ESPHOME on this display by now ?

**Comment by Bogdanel** [comment]
After digging into esphome I managed to have a working config for it, it still needs the touchscreen inserted, but the screen works good

```
esphome:
  name: office-display
  platformio_options:
    board_build.flash_mode: dio
    build_flags:
      -DBOARD_HAS_PSRAM
      -mfix-esp32-psram-cache-issue
    board_build.esp-idf.memory_type: qspi_opi
    board_build.psram_type: opi
    board_build.psram_size: 8MB

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG

### SETUP
i2c:
  id: iic
  sda: 8
  scl: 48

xl9535:
  - id: xl9535_hub
    i2c_id: iic
    address: 0x20

spi:
  clk_pin:
    xl9535: xl9535_hub
    number: 5
  mosi_pin: 
    xl9535: xl9535_hub
    number: 4
  interface: software

display:
  - platform: mipi_rgb
    model: T-RGB-2.1
    update_interval: never



### Display content

lvgl:
  buffer_size: 20%
  

### Backlight

output:
  - platform: ledc
    pin: 46
    frequency: 1000 Hz
    id: pwm_output2

light:
  - platform: monochromatic
    output: pwm_output2
    name: "backlight"
    restore_mode: ALWAYS_ON
```
